### ISSUE TITLE
Гем полностью в не рабочем состоянии...

### ISSUE THREAD

**Issue by krim** [igor-alexandrov/yandex-webmaster#4]
Приветствую.
К сожалнию гем не выполняет практически никакую функцию, кроме как генерацию authorize_url и дальнейшнего логина по ключу.
При получении сайтов получаем пустоту:
webmaster.hosts.first
Faraday::Builder is now Faraday::RackBuilder.
 => #<Yandex::Webmaster::Host href: nil, name: nil, virused: nil, last_access: nil, tcy: nil, url_count: nil, url_errors: nil, index_count: nil, last_week_index_urls: nil, internal_links_count: nil, links_count: nil, last_week_links: nil, total_shows_count: nil, top_shows_percent: nil, top_shows: nil, total_clicks_count: nil, top_clicks_percent: nil, top_clicks: nil, verification: nil, crawling: nil, sitemaps: nil>

**Comment by Nakilon** [comment]
У тебя хоть что-то получилось...

```
webmaster = Yandex::Webmaster.new(:app_id => FOO, :app_password => BAR)

TypeError: superclass mismatch for class DateTime
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/date.rb:3:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
from /Library/Ruby/Gems/2.0.0/gems/multi_xml-0.5.5/lib/multi_xml.rb:3:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
from /Library/Ruby/Gems/2.0.0/gems/oauth2-1.0.0/lib/oauth2/response.rb:2:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
from /Library/Ruby/Gems/2.0.0/gems/oauth2-1.0.0/lib/oauth2.rb:11:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
from /Library/Ruby/Gems/2.0.0/gems/yandex-webmaster-0.2.0/lib/yandex-webmaster/authorization.rb:2:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
from /Library/Ruby/Gems/2.0.0/gems/yandex-webmaster-0.2.0/lib/yandex-webmaster/base.rb:5:in `<top (required)>'
from /Library/Ruby/Gems/2.0.0/gems/yandex-webmaster-0.2.0/lib/yandex-webmaster/client.rb:5:in `<module:Webmaster>'
from /Library/Ruby/Gems/2.0.0/gems/yandex-webmaster-0.2.0/lib/yandex-webmaster/client.rb:4:in `<module:Yandex>'
from /Library/Ruby/Gems/2.0.0/gems/yandex-webmaster-0.2.0/lib/yandex-webmaster/client.rb:3:in `<top (required)>'
from /Library/Ruby/Gems/2.0.0/gems/yandex-webmaster-0.2.0/lib/yandex-webmaster.rb:17:in `new'
from (irb):2
from /usr/bin/irb:12:in `<main>'irb(main):003:0> 
```

**Comment by krim** [comment]
Что конкретно надо?:) Я в итоге не стал заморачиваться с гемом. Получил key и далее использовал апи https://tech.yandex.ru/webmaster/doc/dg/concepts/About-docpage/ . Просто строил GET/POST запросы и отправлял...
